### ISSUE TITLE
Plugin or daemon

### ISSUE THREAD

**Issue by mathstuf** [mathstuf/eventd-plugin-journald#1]
Moving discussion from c80caffa2b to here.

> Say you have several servers, and one desktop/laptop. You run “jounal-eventc-daemon” on each server and you have only one eventd.
> With a plugin, you need one eventd everywhere. :-)

No, I have journald [forward the logs across the network](http://www.freedesktop.org/software/systemd/man/systemd-journal-remote.html).

**Comment by mathstuf** [comment]
@sardemff7

**Comment by sardemff7** [comment]
That was not really necessary (to create an issue to discuss that). :-)

_I_ would make a daemon, but you are, of course, totally free to do whatever you prefer.
Maybe could I call that an API abuse but if you really think this is the way to go for you, do it!

As long as people know where to get support, I am fine with any project using eventd.
Actually, it just surprised me in the first place that you had that much interest in making a plugin!

**Comment by mathstuf** [comment]
I was tired of tracking down the commit :) .

Well, it's a pain when services fail silently. I just want a plumb from failures to notification :) .

**Comment by mathstuf** [comment]
And now tested and working :) .
