### ISSUE TITLE
Plugin id is inappropriately prefixed with "eventd-"

### ISSUE THREAD

**Issue by sardemff7** [mathstuf/eventd-plugin-journald#2]
The "eventd-" prefix is for official plugins only that I maintain along with eventd. :-)

**Comment by mathstuf** [comment]
Documentation please :) . Will fix (or patches welcome ;) ).

**Comment by sardemff7** [comment]
Documented as sardemff7/eventd@910d176125cbcaa5f2ba719f48989b1db1a63173.
